*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 16:43:00 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:30080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 16:44:40 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:30080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:07:40 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:30080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:09:11 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:30080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:16:31 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1104df0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 107, in create
    entry = module.default_app_config
AttributeError: module 'spares' has no attribute 'default_app_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 110, in create
    return cls(entry, module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 40, in __init__
    self.path = self._path_from_module(app_module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 73, in _path_from_module
    "with a 'path' class attribute." % (module, paths))
django.core.exceptions.ImproperlyConfigured: The app module <module 'spares' (namespace)> has multiple filesystem locations (['./spares', '/www/wwwroot/mysite/mysite/spares']); you must configure this app with an AppConfig subclass with a 'path' class attribute.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2022)
spawned uWSGI worker 1 (pid: 2024, cores: 1)
spawned uWSGI worker 2 (pid: 2025, cores: 1)
spawned uWSGI worker 3 (pid: 2026, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:32:01 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1252df0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 121, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for './spares'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2178)
spawned uWSGI worker 1 (pid: 2180, cores: 1)
spawned uWSGI worker 2 (pid: 2181, cores: 1)
spawned uWSGI worker 3 (pid: 2182, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:35:06 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1210e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/www/wwwroot/mysite/mysite/spares'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2339)
spawned uWSGI worker 1 (pid: 2341, cores: 1)
spawned uWSGI worker 2 (pid: 2342, cores: 1)
spawned uWSGI worker 3 (pid: 2343, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:36:08 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1c37e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 107, in create
    entry = module.default_app_config
AttributeError: module 'spares' has no attribute 'default_app_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 110, in create
    return cls(entry, module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 40, in __init__
    self.path = self._path_from_module(app_module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 73, in _path_from_module
    "with a 'path' class attribute." % (module, paths))
django.core.exceptions.ImproperlyConfigured: The app module <module 'spares' (namespace)> has multiple filesystem locations (['/www/wwwroot/mysite/mysite/spares', './spares']); you must configure this app with an AppConfig subclass with a 'path' class attribute.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2426)
spawned uWSGI worker 1 (pid: 2428, cores: 1)
spawned uWSGI worker 2 (pid: 2429, cores: 1)
spawned uWSGI worker 3 (pid: 2430, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:38:03 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x24cddf0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 107, in create
    entry = module.default_app_config
AttributeError: module 'spares' has no attribute 'default_app_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 110, in create
    return cls(entry, module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 40, in __init__
    self.path = self._path_from_module(app_module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 73, in _path_from_module
    "with a 'path' class attribute." % (module, paths))
django.core.exceptions.ImproperlyConfigured: The app module <module 'spares' (namespace)> has multiple filesystem locations (['/www/wwwroot/mysite/mysite/spares', './spares']); you must configure this app with an AppConfig subclass with a 'path' class attribute.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2443)
spawned uWSGI worker 1 (pid: 2445, cores: 1)
spawned uWSGI worker 2 (pid: 2446, cores: 1)
spawned uWSGI worker 3 (pid: 2447, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:41:27 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x169de00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 121, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 207, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 37, in <module>
    raise ImproperlyConfigured('mysqlclient 1.3.13 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.3.13 or newer is required; you have 0.9.3.
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2457)
spawned uWSGI worker 1 (pid: 2459, cores: 1)
spawned uWSGI worker 2 (pid: 2460, cores: 1)
spawned uWSGI worker 3 (pid: 2461, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:42:41 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:30080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x20a1e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x20a1e00 pid: 2526 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2526)
spawned uWSGI worker 1 (pid: 2528, cores: 1)
spawned uWSGI worker 2 (pid: 2529, cores: 1)
spawned uWSGI worker 3 (pid: 2530, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:46:10 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:39080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x25f7e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x25f7e00 pid: 2646 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2646)
spawned uWSGI worker 1 (pid: 2648, cores: 1)
spawned uWSGI worker 2 (pid: 2649, cores: 1)
spawned uWSGI worker 3 (pid: 2650, cores: 1)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:52:08 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:39080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x16f0e00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x16f0e00 pid: 2749 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2749)
spawned uWSGI worker 1 (pid: 2751, cores: 1)
spawned uWSGI worker 2 (pid: 2752, cores: 1)
spawned uWSGI worker 3 (pid: 2753, cores: 1)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:53:18 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xfafe00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xfafe00 pid: 2861 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2861)
spawned uWSGI worker 1 (pid: 2863, cores: 1)
spawned uWSGI worker 2 (pid: 2864, cores: 1)
spawned uWSGI worker 3 (pid: 2865, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:54:01 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:8080).
bind(): Address already in use [core/socket.c line 769]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2863|app: 0|req: 1/1]  () {18 vars in 1172 bytes} [Wed Jul  1 09:54:34 2020]   => generated 0 bytes in 3 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2864|app: 0|req: 1/2]  () {18 vars in 1172 bytes} [Wed Jul  1 09:54:37 2020]   => generated 0 bytes in 2 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2863|app: 0|req: 2/3]  () {18 vars in 1172 bytes} [Wed Jul  1 09:55:54 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2865|app: 0|req: 1/4]  () {18 vars in 1172 bytes} [Wed Jul  1 09:55:55 2020]   => generated 0 bytes in 2 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2864|app: 0|req: 2/5]  () {18 vars in 1172 bytes} [Wed Jul  1 09:55:56 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 17:56:37 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:8080).
bind(): Address already in use [core/socket.c line 769]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2863|app: 0|req: 3/6]  () {18 vars in 1172 bytes} [Wed Jul  1 09:57:05 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2863|app: 0|req: 4/7]  () {18 vars in 1050 bytes} [Wed Jul  1 09:58:06 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2864|app: 0|req: 3/8]  () {16 vars in 944 bytes} [Wed Jul  1 09:58:06 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2865|app: 0|req: 2/9]  () {18 vars in 1050 bytes} [Wed Jul  1 09:58:07 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 2864|app: 0|req: 4/10]  () {20 vars in 997 bytes} [Wed Jul  1 09:58:08 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 18:03:12 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
bind(): Cannot assign requested address [core/socket.c line 769]
Wed Jul  1 13:40:51 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul  1 13:40:51 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul  1 13:40:51 2020 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 21:44:20 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:39080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1030e40
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1030e40 pid: 3401 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3401)
spawned uWSGI worker 1 (pid: 3403, cores: 1)
spawned uWSGI worker 2 (pid: 3404, cores: 1)
spawned uWSGI worker 3 (pid: 3405, cores: 1)
Wed Jul  1 13:45:56 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul  1 13:45:56 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul  1 13:45:56 2020 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 21:46:51 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:39080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 21:54:55 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:39080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 22:25:24 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:39080).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Jul  1 22:31:05 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-39) on 01 July 2020 07:13:20
os: Linux-3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020
nodename: localhost.localdomain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /www/wwwroot/mysite/mysite
writing pidfile to /www/wwwroot/mysite/mysite/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /www/wwwroot/mysite/mysite/
your processes number limit is 3871
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2252de0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 291680 bytes (284 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2252de0 pid: 2177 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2177)
spawned uWSGI worker 1 (pid: 2179, cores: 1)
spawned uWSGI worker 2 (pid: 2180, cores: 1)
spawned uWSGI worker 3 (pid: 2181, cores: 1)
[pid: 2179|app: 0|req: 1/1] 192.168.50.211 () {42 vars in 769 bytes} [Wed Jul  1 14:31:17 2020] GET / => generated 179 bytes in 39 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
[pid: 2181|app: 0|req: 1/2] 192.168.50.211 () {44 vars in 737 bytes} [Wed Jul  1 14:31:18 2020] GET /favicon.ico => generated 179 bytes in 24 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
[pid: 2179|app: 0|req: 2/3] 192.168.50.211 () {40 vars in 750 bytes} [Wed Jul  1 14:31:26 2020] GET /spares => generated 0 bytes in 1 msecs (HTTP/1.1 301) 4 headers in 146 bytes (1 switches on core 0)
[pid: 2180|app: 0|req: 1/4] 192.168.50.211 () {40 vars in 752 bytes} [Wed Jul  1 14:31:26 2020] GET /spares/ => generated 2253 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 137 bytes (1 switches on core 0)
[pid: 2179|app: 0|req: 3/5] 192.168.50.211 () {40 vars in 762 bytes} [Wed Jul  1 14:35:16 2020] GET /spares/sheet => generated 2409 bytes in 12 msecs (HTTP/1.1 200) 4 headers in 137 bytes (1 switches on core 0)
[pid: 2179|app: 0|req: 4/6] 192.168.50.1 () {42 vars in 1120 bytes} [Wed Jul  1 14:35:45 2020] GET / => generated 179 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
[pid: 2181|app: 0|req: 2/7] 192.168.50.1 () {42 vars in 1067 bytes} [Wed Jul  1 14:35:50 2020] GET /favicon.ico => generated 179 bytes in 1 msecs (HTTP/1.1 404) 4 headers in 128 bytes (1 switches on core 0)
[pid: 2180|app: 0|req: 2/8] 192.168.50.1 () {42 vars in 1132 bytes} [Wed Jul  1 14:35:53 2020] GET /spares => generated 0 bytes in 1 msecs (HTTP/1.1 301) 4 headers in 146 bytes (1 switches on core 0)
[pid: 2179|app: 0|req: 5/9] 192.168.50.1 () {42 vars in 1134 bytes} [Wed Jul  1 14:35:53 2020] GET /spares/ => generated 2253 bytes in 2 msecs (HTTP/1.1 200) 4 headers in 137 bytes (1 switches on core 0)
[pid: 2179|app: 0|req: 6/10] 192.168.50.211 () {50 vars in 1007 bytes} [Wed Jul  1 14:51:56 2020] POST /spares/jump/ => generated 145 bytes in 66 msecs (HTTP/1.1 500) 5 headers in 154 bytes (1 switches on core 0)
[pid: 2181|app: 0|req: 3/11] 192.168.50.211 () {42 vars in 786 bytes} [Wed Jul  1 14:52:01 2020] GET /spares/datatables?_=1593586325829 => generated 145 bytes in 55 msecs (HTTP/1.1 500) 5 headers in 154 bytes (1 switches on core 0)
